### ISSUE TITLE
feat: right click to copy commit hash

### ISSUE THREAD

**Issue by ZanMinKian** [Saber2pr/vsc-file-git-history#2]
## Feature request

希望增加功能：右键，然后复制commit节点的hash。这样方便在其他插件搜索到对应的提交记录。

**Comment by Saber2pr** [comment]
支持了，升级到v0.0.17

**Comment by ZanMinKian** [comment]
感谢作者，真乃神人。

但是有个bug，在网页版vscode不生效，比如通过如下方式进去，然后右键复制commit id，但是并没有生效。或者给作者提一个小建议，`FILE GIT HISTORY`下的每一行有没有办法能复制文字，这样也能解决用户需求。
![image](https://user-images.githubusercontent.com/35495628/208820604-d6200fb8-6243-4cb6-815c-63f5c9e3e13d.png)

![image](https://user-images.githubusercontent.com/35495628/208820585-66500023-019c-425d-97ae-3be1e1f31501.png)

**Comment by Saber2pr** [comment]
> 感谢作者，真乃神人。
> 
> 但是有个bug，在网页版vscode不生效，比如通过如下方式进去，然后右键复制commit id，但是并没有生效。或者给作者提一个小建议，`FILE GIT HISTORY`下的每一行有没有办法能复制文字，这样也能解决用户需求。 ![image](https://user-images.githubusercontent.com/35495628/208820604-d6200fb8-6243-4cb6-815c-63f5c9e3e13d.png)
> 
> ![image](https://user-images.githubusercontent.com/35495628/208820585-66500023-019c-425d-97ae-3be1e1f31501.png)

修复了，codespace里升级一下插件到 v0.0.18

**Comment by ZanMinKian** [comment]
@Saber2pr 感谢👍

**Comment by ZanMinKian** [comment]
再提一个小小的建议，复制commit id时，能不能不要右下角弹出一个提示啊？如果复制失败弹出提示更加友好点，复制成功也提示，就显得比较多余。

编程很多时候讲究心流，右下角随便弹出提示会打断用户心流，体验不是很好。作者可以考虑一下。

**Comment by Saber2pr** [comment]
> 再提一个小小的建议，复制commit id时，能不能不要右下角弹出一个提示啊？如果复制失败弹出提示更加友好点，复制成功也提示，就显得比较多余。
> 
> 编程很多时候讲究心流，右下角随便弹出提示会打断用户心流，体验不是很好。作者可以考虑一下。

可以的，加提示就是为了避免出现剪贴板写入失败的情况，可以手动从提示里选中复制
