### ISSUE TITLE
Display the commit timestamp

### ISSUE THREAD

**Issue by zanminkian** [Saber2pr/vsc-file-git-history#4]
## Feature request

能在最前面展示提交时间，方便浏览文件更改时间，从而更快定位到文件什么时候改动的。
比如：
` [20210108 12:12:00]-77d277a: fix(xxx): xxx +10|-2`
` [20210108 13:12:00]-abd272d: fix(xxx): xxx +10|-2`

**Comment by Saber2pr** [comment]
可以了，不错的idea！👍

**Comment by zanminkian** [comment]
🐮
