### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zanminkian** [Saber2pr/vsc-file-git-history#5]
## Feature request
1. 使用等宽字符，不确定vscode能不能支持，作者可以考虑看看，等宽字符起码能让内容展示更美观。
2. commit id 其实可以不用展示了，因为右键已经能复制commit id。有了commit id，整个内容会很长，反而不好看清后面commit message。正常开发也不太看commit id。
3. 右上角的刷新按钮，一点击就reload了整个页面（在github codespace上），体验不好。可以考虑去掉（目前没发现有什么用），或者局部刷新。

**Comment by zanminkian** [comment]
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/35495628/221488196-b8c45dd5-6601-4f2d-9709-23c3f8cf27e6.png">

**Comment by Saber2pr** [comment]
1. 查了下应该不行。要么改用webview渲染列表
2. 隐藏了，确实好一些
3. 有时候commit历史出不来，就加了一个刷新（reload编辑器），局部刷新还没找到好方法
