### ISSUE TITLE
显示该文件提交的作者

### ISSUE THREAD

**Issue by huangcs427** [Saber2pr/vsc-file-git-history#6]
## Feature request

Describe your needs.
如果显示了作者名应该会更好, 因为有时候需要看下是谁提交的.

比如这个软件:
![image](https://user-images.githubusercontent.com/31842636/232644132-bf63ca2f-83d0-4496-b581-ca917fba883a.png)

**Comment by Saber2pr** [comment]
可以的，这里已经解析出作者信息，展示出来就好了
https://github.com/Saber2pr/vsc-file-git-history/blob/master/src/utils/git.ts#L68-L71

**Comment by Saber2pr** [comment]
已发布 v0.0.23

**Comment by huangcs427** [comment]
这么高效率， 谢谢
