### ISSUE TITLE
git fatal error: file is outside directory

### ISSUE THREAD

**Issue by juanfcocontreras** [Saber2pr/vsc-file-git-history#7]
## Description

For folders in paths containing whitespace, the extension causes the error `"git fatal error: file is outside directory"` every time I access the Git tab. I'm on MacOS 13 Ventura, and whether I enable or disable the `precomposeunicode` and `ignorecase` options for the repo. If I disable the extension, the errors don't appear.

## Platform

MacOS 13 Ventura

## Version

File Git History 0.0.24

## Error Log

`git fatal error: file is outside directory`

**Comment by Saber2pr** [comment]
fixed at saber2pr.file-git-history `v0.0.25`. ~
